[build]
  PHP_VERSION=7.3

[[redirects]]
  from = "/dev/*"
  to = "/"
[[redirects]]
  from = "/tests/*"
  to = "/"
[[redirects]]
  from = "/model/*"
  to = "/"
[[redirects]]
  from = "/view/*"
  to = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"